kind: Namespace
apiVersion: v1
metadata:
  name: todos-dev
---
kind: Namespace
apiVersion: v1
metadata:
  name: todos-prod
---
kind: Namespace
apiVersion: v1
metadata:
  name: todos-azure
